 CREATE TABLE USERS(
   ID  SERIAL PRIMARY KEY,
   NAME           TEXT      NOT NULL,
   EMAIL          TEXT       NOT NULL,
   PASSWORD       TEXT      NOT NULL,
   PHONE          TEXT      NOT NULL,
   HOBBIES        TEXT,
   ORGANIZATION   TEXT,
   QUALIFICATION  TEXT,
   FOOD           TEXT
);

INSERT INTO USERS (NAME,EMAIL,PASSWORD,PHONE)
VALUES ( 'Paul', 'hiteshgupta3012@gmail.com', 'hitesh', '8559093899' );